sudo: required
services:
  - docker

before_install:
  - docker build -t random09/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run random09/react-test npm test -- --coverage

after_success:
  - docker build -t random09/multi-client ./client
  - docker build -t random09/multi-server ./server
  - docker build -t random09/multi-nginx ./nginx
  - docker build -t random09/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push random09/multi-client
  - docker push random09/multi-server
  - docker push random09/multi-nginx
  - docker push random09/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-444083742860
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
